update_all_signals:
  cron: "*/10 * * * *"
  class: "UpdateAllAvailableSignalsJob"
  queue: "default"
  active_job: true

convert_orders_to_positions:
  cron: "*/9 * * * *"
  class: "IgConvertOrdersToPositionsJob"
  queue: "default"
  active_job: true

update_closed_positions:
  cron: "*/11 * * * *"
  class: "IgUpdateClosedPositionsJob"
  queue: "default"
  active_job: true

close_positions:
  cron: "*/5 * * * *"
  class: "IgClosePositionsJob"
  queue: "default"
  active_job: true
