convert_orders_to_positions:
  cron: "*/9 * * * *"
  class: "IG::ConvertOrdersToPositionsJob"
  queue: "default"
  active_job: true

update_closed_positions:
  cron: "*/11 * * * *"
  class: "IG::UpdateClosedPositionsJob"
  queue: "default"
  active_job: true

# lfs_generate_signals_from_emails:
#   cron: "*/2 * * * *"
#   class: "Lfs::GenerateSignalsFromEmailsJob"
#   queue: "default"
#   active_job: true

terminate_positions:
  cron: "*/4 * * * *"
  class: "IG::TerminatePositionsJob"
  queue: "default"
  active_job: true
