convert_orders_to_positions:
  cron: "*/3 * * * *"
  class: "IG::ConvertOrdersToPositionsJob"
  queue: "default"
  active_job: true

update_closed_positions:
  cron: "*/11 * * * *"
  class: "IG::UpdateClosedPositionsJob"
  queue: "default"
  active_job: true

terminate_positions:
  cron: "*/4 * * * *"
  class: "IG::TerminatePositionsJob"
  queue: "default"
  active_job: true
    
fs_generate_signals_from_emails:
  cron: "*/2 * * * *"
  class: "Fs::GenerateSignalsFromEmailsJob"
  queue: "default"
  active_job: true

fx_premiere_generate_signals_from_emails:
  cron: "*/2 * * * *"
  class: "FxPremiere::GenerateSignalsFromEmailsJob"
  queue: "default"
  active_job: true

pia_first_generate_signals_from_emails:
  cron: "*/2 * * * *"
  class: "PiaFirst::GenerateSignalsFromEmailsJob"
  queue: "default"
  active_job: true
