concurrency: 2
development:
  pidfile: tmp/pids/sidekiq_development.pid
  logfile: log/sidekiq_development.log
production:
  pidfile: /tmp/sidekiq.pid
  logfile: log/sidekiq_production.log
:queues:
  - default
  - update_pair_price
  - shark.production.default
  - shark.development.default
  - shark.production.update_pair_price
  - shark.development.update_pair_price
